from __future__ import annotations

from typing import Any

from datashield.detectors.pattern_matcher import PatternMatcher
from datashield.scanner import (
    BaseDetector,
    Confidence,
    DataCategory,
    DetectorType,
    Finding,
    Severity,
)

_SECRET_PATTERNS: list[tuple[str, str, Severity, Confidence, DataCategory, str]] = [
    (
        "aws_access_key",
        r"AKIA[0-9A-Z]{16}",
        Severity.CRITICAL,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "AWS Access Key ID",
    ),
    (
        "aws_secret_key",
        r"(?i)(?<![a-zA-Z0-9])[\w\/+=]{40}(?![a-zA-Z0-9])",
        Severity.CRITICAL,
        Confidence.MEDIUM,
        DataCategory.CREDENTIAL,
        "AWS Secret Access Key",
    ),
    (
        "github_pat",
        r"(?i)ghp_[a-zA-Z0-9]{36}",
        Severity.CRITICAL,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "GitHub Personal Access Token",
    ),
    (
        "github_fine_grained",
        r"(?i)github_pat_[a-zA-Z0-9]{82}",
        Severity.CRITICAL,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "GitHub Fine-Grained Token",
    ),
    (
        "gitlab_token",
        r"(?i)glpat-[a-zA-Z0-9\-]{20,}",
        Severity.CRITICAL,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "GitLab Personal Access Token",
    ),
    (
        "slack_token",
        r"(?i)xox[baprs]-[a-zA-Z0-9\-]{20,}",
        Severity.CRITICAL,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "Slack Token",
    ),
    (
        "slack_webhook",
        r"https://hooks\.slack\.com/services/[A-Za-z0-9/]{40,}",
        Severity.CRITICAL,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "Slack Webhook URL",
    ),
    (
        "stripe_live",
        r"(?i)sk_live_[a-zA-Z0-9]{20,}",
        Severity.CRITICAL,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "Stripe Live Secret Key",
    ),
    (
        "stripe_test",
        r"(?i)sk_test_[a-zA-Z0-9]{20,}",
        Severity.MEDIUM,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "Stripe Test Secret Key",
    ),
    (
        "google_api_key",
        r"(?i)AIza[0-9A-Za-z\-_]{35}",
        Severity.HIGH,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "Google API Key",
    ),
    (
        "google_oauth",
        r"\d{10,20}-[a-zA-Z0-9_]{30,40}\.apps\.googleusercontent\.com",
        Severity.HIGH,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "Google OAuth Client ID",
    ),
    (
        "twilio_sid",
        r"(?i)AC[a-zA-Z0-9]{32}",
        Severity.HIGH,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "Twilio Account SID",
    ),
    (
        "twilio_token",
        r"(?i)[a-zA-Z0-9]{32}",
        Severity.MEDIUM,
        Confidence.LOW,
        DataCategory.CREDENTIAL,
        "Potential Twilio Auth Token",
    ),
    (
        "heroku_api",
        r"(?i)[hH][eE][rR][oO][kK][uU].*[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}",
        Severity.HIGH,
        Confidence.MEDIUM,
        DataCategory.CREDENTIAL,
        "Heroku API Key",
    ),
    (
        "pgp_private_block",
        r"-----BEGIN PGP PRIVATE KEY BLOCK-----",
        Severity.CRITICAL,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "PGP Private Key Block",
    ),
    (
        "ssh_private_key",
        r"-----BEGIN (?:RSA |EC |DSA |OPENSSH )?PRIVATE KEY-----",
        Severity.CRITICAL,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "SSH/RSA Private Key",
    ),
    (
        "jwt_token",
        r"eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,}",
        Severity.HIGH,
        Confidence.MEDIUM,
        DataCategory.SECRET,
        "JWT Token",
    ),
    (
        "azure_connection_string",
        r"(?i)DefaultEndpointsProtocol=https;AccountName=[a-zA-Z0-9]+;AccountKey=[a-zA-Z0-9+/=]{40,}",
        Severity.CRITICAL,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "Azure Connection String",
    ),
    (
        "docker_auth",
        r"(?i)auth\s*['\"]?\s*:\s*['\"][a-zA-Z0-9+/=]{20,}['\"]",
        Severity.HIGH,
        Confidence.MEDIUM,
        DataCategory.CREDENTIAL,
        "Docker Registry Auth",
    ),
    (
        "npm_token",
        r"(?i)npm_[a-zA-Z0-9]{36}",
        Severity.HIGH,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "npm Access Token",
    ),
    (
        "pypi_token",
        r"(?i)pypi-[a-zA-Z0-9]{40}",
        Severity.HIGH,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "PyPI API Token",
    ),
    (
        "discord_token",
        r"(?i)[a-zA-Z0-9_-]{24}\.[a-zA-Z0-9_-]{6}\.[a-zA-Z0-9_-]{24,}",
        Severity.HIGH,
        Confidence.MEDIUM,
        DataCategory.CREDENTIAL,
        "Discord Bot Token",
    ),
    (
        "telegram_token",
        r"\d{8,10}:[a-zA-Z0-9_-]{35}",
        Severity.HIGH,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "Telegram Bot Token",
    ),
    (
        "generic_api_key",
        r"(?i)(?:api[_-]?key|apikey|api[_-]?secret|app[_-]?secret)\s*[=:]\s*['\"]?([a-zA-Z0-9_\-]{16,})['\"]?",
        Severity.HIGH,
        Confidence.MEDIUM,
        DataCategory.SECRET,
        "Generic API Key",
    ),
    (
        "password_field",
        r"(?i)(?:password|passwd|pwd|secret|token)\s*[=:]\s*['\"]?([^'\"\s]{8,})['\"]?",
        Severity.CRITICAL,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "Password/Secret in plaintext",
    ),
    (
        "connection_string",
        r"(?i)(?:jdbc|mysql|postgres|mongodb|redis|amqp)://[^\s]+",
        Severity.HIGH,
        Confidence.HIGH,
        DataCategory.SECRET,
        "Database connection string with credentials",
    ),
    (
        "bearer_auth",
        r"(?i)(?:bearer|token)\s+[a-fA-F0-9]{8,}",
        Severity.HIGH,
        Confidence.MEDIUM,
        DataCategory.CREDENTIAL,
        "Bearer authentication token",
    ),
    (
        "basic_auth",
        r"(?i)Basic\s+[a-zA-Z0-9+/=]{10,}",
        Severity.HIGH,
        Confidence.MEDIUM,
        DataCategory.CREDENTIAL,
        "Basic auth credentials detected",
    ),
    (
        "authorization_header",
        r"(?i)authorization:\s*(?:basic|bearer|digest)\s+[^\s]+",
        Severity.HIGH,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "Authorization header",
    ),
    (
        "private_key_content",
        r"-----BEGIN.*KEY-----[\s\S]*?-----END.*KEY-----",
        Severity.CRITICAL,
        Confidence.HIGH,
        DataCategory.CREDENTIAL,
        "Embedded private key",
    ),
    (
        "hashicorp_token",
        r"(?i)(?:token|vault|consul|nomad)\s*[=:]\s*['\"]?[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}['\"]?",
        Severity.MEDIUM,
        Confidence.LOW,
        DataCategory.CREDENTIAL,
        "Potential HashiCorp token",
    ),
    (
        "otp_secret",
        r"(?i)(?:otp|totp|hotp|2fa|mfa|secret)\s*[=:]\s*[A-Z2-7]{16,}",
        Severity.HIGH,
        Confidence.MEDIUM,
        DataCategory.CREDENTIAL,
        "OTP/2FA Secret",
    ),
    (
        "s3_url",
        r"s3://[a-zA-Z0-9.\-_]+/[a-zA-Z0-9.\-_/]+",
        Severity.MEDIUM,
        Confidence.MEDIUM,
        DataCategory.SECRET,
        "S3 URL (may expose bucket names)",
    ),
]


class SecretScanner(BaseDetector):
    """Detects secrets and credentials (API keys, tokens, passwords, certificates, private keys)."""

    name = "secret_scanner"
    detector_type = DetectorType.SECRET

    def __init__(self) -> None:
        self._matcher = PatternMatcher(_SECRET_PATTERNS)

    async def detect(self, records: list[dict[str, Any]]) -> list[Finding]:
        return await self._matcher.detect(records)
