from __future__ import annotations

from jinja2 import Template

from datashield.scanner import ScanReport

_HTML_TEMPLATE = Template(
    """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>DataShield Report - {{ report.id }}</title>
<style>
* { margin: 0; padding: 0; box-sizing: border-box; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; color: #333; padding: 2rem; }
.container { max-width: 1000px; margin: 0 auto; }
h1 { color: #1a1a2e; margin-bottom: 0.5rem; }
h2 { color: #16213e; margin: 1.5rem 0 0.5rem; }
.meta { color: #666; font-size: 0.9rem; margin-bottom: 1.5rem; }
.score-card { background: linear-gradient(135deg, {{ gradient }}); color: white; padding: 1.5rem; border-radius: 12px; margin-bottom: 1.5rem; }
.score-card h2 { color: white; margin-top: 0; }
.score-card .score { font-size: 2.5rem; font-weight: bold; }
.score-card .label { opacity: 0.9; }
.summary { display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr)); gap: 1rem; margin-bottom: 1.5rem; }
.stat-card { background: white; padding: 1rem; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); text-align: center; }
.stat-card .value { font-size: 1.8rem; font-weight: bold; color: #16213e; }
.stat-card .label { font-size: 0.8rem; color: #666; text-transform: uppercase; }
.finding { background: white; padding: 1rem; border-radius: 8px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); margin-bottom: 0.75rem; border-left: 4px solid {{ border_color }}; }
.finding .header { display: flex; justify-content: space-between; margin-bottom: 0.5rem; }
.finding .title { font-weight: 600; }
.finding .severity { font-size: 0.8rem; padding: 0.2rem 0.5rem; border-radius: 4px; font-weight: 600; }
.severity-critical { background: #ffebee; color: #c62828; }
.severity-high { background: #fce4ec; color: #ad1457; }
.severity-medium { background: #fff8e1; color: #f57f17; }
.severity-low { background: #e3f2fd; color: #1565c0; }
.severity-info { background: #f3e5f5; color: #7b1fa2; }
.finding .detail { font-size: 0.85rem; color: #666; }
.finding .detail span { margin-right: 1rem; }
pre { background: #f8f9fa; padding: 0.5rem; border-radius: 4px; overflow-x: auto; font-size: 0.8rem; margin-top: 0.5rem; }
footer { text-align: center; color: #999; font-size: 0.8rem; margin-top: 2rem; padding-top: 1rem; border-top: 1px solid #eee; }
</style>
</head>
<body>
<div class="container">
<h1>DataShield Privacy Report</h1>
<p class="meta">Report ID: {{ report.id }} | Generated: {{ report.timestamp }}</p>

<div class="score-card">
<h2>Risk Assessment</h2>
<div class="score">{{ "%.1f"|format(report.risk_score) }}/100</div>
<div class="label">{{ report.risk_category|upper }}</div>
</div>

<div class="summary">
<div class="stat-card"><div class="value">{{ report.total_findings }}</div><div class="label">Findings</div></div>
<div class="stat-card"><div class="value">{{ report.total_records }}</div><div class="label">Records</div></div>
<div class="stat-card"><div class="value">{{ report.summary.get('critical', 0) }}</div><div class="label">Critical</div></div>
<div class="stat-card"><div class="value">{{ report.summary.get('high', 0) }}</div><div class="label">High</div></div>
<div class="stat-card"><div class="value">{{ report.summary.get('medium', 0) }}</div><div class="label">Medium</div></div>
<div class="stat-card"><div class="value">{{ report.summary.get('low', 0) }}</div><div class="label">Low</div></div>
</div>

{% if report.findings %}
<h2>Findings ({{ report.findings|length }})</h2>
{% for f in report.findings %}
<div class="finding">
<div class="header">
<span class="title">{{ f.title }}</span>
<span class="severity severity-{{ f.severity.value }}">{{ f.severity.value|upper }}</span>
</div>
<div class="detail">
<span>Detector: {{ f.detector }}</span>
<span>Category: {{ f.category.value }}</span>
<span>Confidence: {{ f.confidence.value }}</span>
{% if f.field_path %}<span>Field: {{ f.field_path }}</span>{% endif %}
</div>
{% if f.snippet %}<pre>{{ f.snippet[:300] }}</pre>{% endif %}
{% if f.recommendation %}<div style="margin-top: 0.5rem; font-size: 0.85rem; color: #666;"><strong>Recommendation:</strong> {{ f.recommendation }}</div>{% endif %}
</div>
{% endfor %}
{% endif %}

<footer>Generated by <strong>DataShield</strong> &mdash; Privacy-Preserving Data Sanitization for AI Training</footer>
</div>
</body>
</html>""",
    autoescape=True,
)


class HTMLReporter:
    def render(self, report: ScanReport) -> str:
        severity_colors = {
            "critical": "#ff4444",
            "high": "#ff6b6b",
            "medium": "#ffa726",
            "low": "#42a5f5",
            "safe": "#66bb6a",
        }
        cat = report.risk_category
        if cat in ("critical", "high"):
            gradient = "#ff416c, #ff4b2b"
            border_color = severity_colors.get(cat, "#ff4444")
        elif cat == "medium":
            gradient = "#f7971e, #ffd200"
            border_color = "#f7971e"
        elif cat == "low":
            gradient = "#00b4db, #0083b0"
            border_color = "#00b4db"
        else:
            gradient = "#11998e, #38ef7d"
            border_color = "#11998e"

        return _HTML_TEMPLATE.render(
            report=report,
            gradient=gradient,
            border_color=border_color,
        )
